### ISSUE TITLE
Error in URL link on page

### ISSUE THREAD

**Issue by mlnelson-ibm** [ibm-cloud-docs/fortigate-1g#8]
Link on page https://cloud.ibm.com/docs/fortigate-1g?topic=fortigate-1g-about-fortigate-security-appliance-1gbps that is suppose to direct to http://www.fortinet.com/sites/default/files/productdatasheets/FortiGate-300C.pdf (labelled FortiGate 1 Gpbs) now goes redirects to a search of resources and documentation and not the product data sheet that is linked.

**Comment by jbmitch** [comment]
File removed, as 1g no longer supported. Removing link,
