### ISSUE TITLE
What are the default DNS servers of FortiGate 1 Gbps?

### ISSUE THREAD

**Issue by tetsuonatom** [ibm-cloud-docs/fortigate-1g#9]
```
What are the default DNS servers of FortiGate 1 Gbps?

By default, FortiGate uses the following FortiGuard's DNS servers.

    Primary: 208.91.112.53
    Secondary: 208.91.112.52
```
Could you add the above FAQ in "FAQs for FortiGate Security Appliance 1 Gbps" like the following FAQ in 10G?

https://cloud.ibm.com/docs/fortigate-10g?topic=fortigate-10g-faqs-for-fortigate-security-appliance-10gbps&locale=en#what-are-the-default-dns-servers-of-fortigate-10-gbps-

**Comment by austinmama** [comment]
Added: https://test.cloud.ibm.com/docs/fortigate-1g?topic=fortigate-1g-faqs-for-fortigate-security-appliance-1gbps

**Comment by austinmama** [comment]
@jbmitch  Please close this issue.
